# Generated by Django 5.2.7 on 2025-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_news_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
